name: nf-core template version comment
# This workflow is triggered on PRs to check if the pipeline template version matches the latest nf-core version.
# It posts a comment to the PR, even if it comes from a fork.

jobs:
  template_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Read template version from .nf-core.yml
        uses: nichmor/minimal-read-yaml@1f7205277e25e156e1f63815781db80a6d490b8f # v0.0.2
        id: read_yml
        with:
          config: ${{ github.workspace }}/.nf-core.yml

      - name: Install nf-core
        run: |
          python -m pip install --upgrade pip
          pip install nf-core==${{ steps.read_yml.outputs['nf_core_version'] }}

      - name: Check nf-core outdated
        id: nf_core_outdated
        run: echo "OUTPUT=$(pip list --outdated | grep nf-core)" >> ${GITHUB_ENV}
